---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Volume Action
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: ansiblevol1
      vserver: nltl_cifs_marks
      aggregate_name: nltl_fas8200_01_SAS_1
      size: 30
      size_unit: gb
      comment: ansible created volume
      hostname: "10.64.32.30"
      username: "admin"
      password: "one4all+1"
      https: true
      validate_certs: false

  - name: Create lun
    na_ontap_lun:
      state: present
      name: ansibleLUN
      flexvol_name: ansiblevol1
      vserver: nltl_cifs_marks
      size: 5
      size_unit: gb
      os_type: linux
      space_reserve: True
      hostname: "10.64.32.30"
      username: "admin"
      password: "one4all+1"
      https: true
      validate_certs: false
