---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Volume Action
  tasks:
  - name: Create SVM
    netapp.ontap.na_ontap_svm:
      state: present
      name: ansibleVServer
      root_volume: vol1
      root_volume_aggregate: nltl_fas8200_01_SAS_1
      root_volume_security_style: mixed
      hostname: "10.64.32.30"
      username: "admin"
      password: "one4all+1"
      https: true
      validate_certs: false