---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Volume Action
  vars_prompt:
    - name: "cluster"
      prompt: "Please enter the cluster name or IP Address"
      private: no

    - name: "username"
      prompt: "Please enter the username"
      private: no

    - name: "password"
      prompt: "Please enter password"
      private: yes
  vars:
    login: &login
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false  
    vserver: ansibleVServer
    aggr: nltl_fas8200_01_SAS_1
    vol_name: ansiblevol1
  tasks:
  - name: Create SVM
    netapp.ontap.na_ontap_svm:
      state: present
      name: ansibleVServer
      root_volume: vol1
      root_volume_aggregate: nltl_fas8200_01_SAS_1
      root_volume_security_style: mixed
      <<: *login
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 10
      size_unit: gb
      <<: *login