---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Volume Action
  vars:
    vserver: nltl_cifs_marks
    aggregate_name: nltl_fas8200_01_SAS_1
    vol_name: ansiblevol1
  tasks:
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 10
      size_unit: gb
      comment: ansible created
      hostname: 10.64.32.30
      username: admin
      password: one4all+1
      https: true
      validate_certs: false