---
- hosts: localhost
  collections:
    - netapp.ontap
  name: Volume Action

  vars_prompt:

    - name: "cluster"
      prompt: "Please enter the cluster name or IP Address"
      private: no

    - name: "username"
      prompt: "Please enter the username"
      private: no

    - name: "password"
      prompt: "Please enter password"
      private: yes

  vars:
    name: ansiblevol1
    vserver: nltl_cifs_marks
    aggregate_name: nltl_fas8200_01_SAS_1 
    login: &login
      hostname: "{{ cluster }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false  
  
  tasks:       
  - name: Volume Create
    na_ontap_volume:
      state: present
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 10
      size_unit: gb
      <<: *login