--- 
- hosts: localhost 
  name: Setup ONTAP 
  vars: 
    hostname: "10.64.32.30" 
    username: "admin" 
    vol_name: ansiblevol1
    vserver: nltl_cifs_marks
    aggr: nltl_fas8200_01_SAS_1
    state: present 
    https: true
    validate_certs: false
  vars_prompt: 
  - name: "password" 
    prompt: "Password:" 
  tasks: 
  - name: Volume Create
    na_ontap_volume:
      state: "{{ state }}"
      name: "{{ vol_name }}"
      vserver: "{{ vserver }}"
      aggregate_name: "{{ aggr }}"
      size: 10
      size_unit: gb
      comment: ansible created volume
      hostname: "{{ hostname }}" 
      username: "{{ username }}" 
      password: "{{ password }}" 