---
- hosts: localhost
  collections:
    - netapp.storagegrid
  vars_files:
    /home/nelim99/git/storagegrid-automating-deployment/ansible-playbooks/01-sg_vars.yaml
  gather_facts: no
  tasks:
- name: Get Grid Authorization token
  uri:
    url: "https://10.64.34.12/api/v3/authorize"
    method: POST
    body: {
      "username": "root",
      "password": "netapp01",
      "cookie": false,
      "csrfToken": false
    }
    body_format: json
    validate_certs: false
  register: auth

- name: Create a StorageGRID Tenant Account
  netapp.storagegrid.na_sg_grid_account:
    api_url: "https://sgadmin.example.com"
    auth_token: "{{ auth.json.data }}"
    validate_certs: false
    state: present
    name: AnsibleTenant
    protocol: s3
    management: true
    use_own_identity_source: true
    allow_platform_services: true
    password: "mytenantrootpassword"
    quota_size: 10