---
- hosts: localhost
  name: Get ONTAP Info
  gather_facts: false
   

  collections:
    - netapp.ontap

  vars_prompt:

    - name: "cluster"
      prompt: "Please enter the cluster name or IP Address"
      private: no

    - name: "username"
      prompt: "Please enter the username"
      private: no

    - name: "password"
      prompt: "Please enter password"
      private: yes

  vars:
    login: &login
      hostname: "{{ cluster }}"
      username: "{{ username }}"
      password: "{{ password }}"
      https: true
      validate_certs: false

  tasks:

  - name: Get ONTAP info
    na_ontap_info:
      gather_subset:
        - ontap_system_version
      <<: *login
    register: ontap_info

  - debug:
      msg: "{{ ontap_info.ontap_info }}"